### ISSUE TITLE
Applicability of Chronos on smaller libraries

### ISSUE THREAD

**Issue by j-andrews7** [broadinstitute/chronos#13]
This is a general question regarding use of Chronos on smaller libraries, e.g. < 10000 gRNAs total. 

Are there any considerations to keep in mind in such cases? Specific parameters that should be tweaked? Is there a lower limit on library size for analysis via Chronos?

**Comment by joshdempster** [comment]
Hi j, there's two parameters you might want to adjust if your library is very small. One is `kernel_width`. This parameter is part of Chronos's smooth hierarchical constraint that encourages the trend line of gene effects between any two cell lines to be close to the diagonal. The kernel width controls how many genes are considered for this penalty. The default is 50. You might want to shrink this (as low as 10 should be ok) if you have less than 1,000 genes, although I doubt it would make a big difference. 

The other parameter is `cell_efficacy_guide_quantile`. Chronos estimates the cell efficacy (the maximum possible depletion achievable by any guide, equivalent to Cas activity) at the beginning of the run. It finds the overall X% most depleting guides, and looks within each cell line at how depleted those guides are. If you have a library with less than 1,000 guides, the default value of 0.02 means Chronos is using less than 20 guides to make this estimate, and the estimate could become noisy. So you might want to raise this parameter a bit.

**Comment by j-andrews7** [comment]
Appreciate the suggestions, thanks.
