### ISSUE TITLE
Image size error

### ISSUE THREAD

**Issue by anna-alemany** [broadinstitute/chronos#3]
Dear chronos coders, 

We are trying to run your pipeline in our CRISPR screen. The dimensions of our readcounts matrix are 46x37722. When running the reports.qc_initial_data line, we get a ValueError saying that the Image size of 1500x283800 pixels is too large. It must be less than 2^16 in each direction. We have unsuccessfully been looking at the source code to try to understand where this comes from. Could you help us out? 

Thanks!

**Comment by joshdempster** [comment]
Hi Anna, can you provide the full traceback?
